plugins:
  - jest
env:
  browser: true
  es2021: true
  node: true
extends: 
  - 'airbnb-base'
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-console": 0,
  "import/extensions": 0,
  "import/no-relative-packages": 0,
  "no-alert": "off",
  "func-names": "off",
  "quote-props": "off",
  "quotes": "off",
  "key-spacing": "off",
  "no-unused-vars": "off",
  "no-param-reassign": "off",
  "no-undef": "off",
}
