env:
  browser: true
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "import/extensions": 0,
  "import/no-relative-packages": 0,
  "no-alert": "off",
  "func-names": "off",
  "quote-props": "off",
  "quotes": "off",
  "key-spacing": "off",
}
